trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: marketflow-secrets
  - name: TF_WORKING_DIR
    value: infra/env/dev.0

stages:
  - stage: Terraform_Deploy
    displayName: "Terraform Init, Plan & Apply"
    jobs:
      - job: terraform
        displayName: "Deploy MarketFlow Infrastructure"
        steps:

          # 1️⃣ Установить Terraform
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.8.5'

          # 2️⃣ Init
          - task: TerraformTaskV4@4
            displayName: "Terraform Init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(TF_WORKING_DIR)'
              backendServiceArm: 'marketflow-azure-connection'

          # 3️⃣ Plan
          - task: TerraformTaskV4@4
            displayName: "Terraform Plan"
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(TF_WORKING_DIR)'
              environmentServiceNameAzureRM: 'marketflow-azure-connection'
              commandOptions: '-out=tfplan'

          # 4️⃣ Apply
          - task: TerraformTaskV4@4
            displayName: "Terraform Apply"
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(TF_WORKING_DIR)'
              environmentServiceNameAzureRM: 'marketflow-azure-connection'
              commandOptions: 'tfplan'
